project:
  type: website
  
website:
  site-url: https://tom-pollak.github.io/
  page-footer:
    center:
      - text: "Home"
        href: https://tom-pollak.github.io/
      - icon: github
        href: https://github.com/tom-pollak/
        aria-label: GitHub
    
theme: [darkly, styles.scss]
format:
  html:
    embed-resources: true
    self-contained-math: false
    highlight-style: gruvbox-dark
