website:
  site-url: https://tom-pollak.github.io/
  page-footer:
    center:
      - text: "Home"
        href: https://tom-pollak.github.io/
      - icon: github
        href: https://github.com/tom-pollak/
        aria-label: GitHub
output-dir: pages
theme: [darkly, black.scss]
format:
  html:
    embed-resources: true
    self-contained-math: false
format-links: false
# sidebar: false
