website:
  site-url: https://tom-pollak.github.io/
theme: [darkly, black.scss]
format:
  html:
    embed-resources: false
    self-contained-math: false
  revealjs:
    html-math-method: mathjax
body-footer: TEST STSTSTEWTWATFD
